name: baraneq
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
####################### basic ############################
  dartz: ^0.10.1
  dio: ^5.3.2
  get_it: ^7.6.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_offline: ^3.0.0
  internet_connection_checker: ^1.0.0+1
  jwt_decode: ^0.3.1
  flutter_screenutil: ^5.9.0
  page_transition: ^2.0.9
  path_provider: ^2.1.1
  persistent_bottom_nav_bar: ^5.0.2
  secure_shared_preferences: ^0.0.4
  supercharged: ^2.1.1
  google_fonts: ^6.1.0
  url_launcher: ^6.1.14
  introduction_screen: ^3.1.12
  avatar_glow: ^3.0.1
  image_picker: ^1.0.4
  #material_floating_search_bar_2: ^0.5.0
  loader_overlay: ^4.0.0
  quickalert: ^1.1.0
####################### Not used ############################
  # cached_network_image: ^3.2.3
  # geocoding: ^2.1.0
  # geolocator: ^10.0.0 
  # flutter_map: ^6.1.0
  # google_maps_flutter: ^2.5.0
  # google_nav_bar: ^5.0.6
  # latlong2: ^0.9.0
  # pinput: ^4.0.0
  # shimmer: ^3.0.0
  # simple_animations: ^5.0.2
  # lottie: ^3.0.0
  # card_swiper: ^3.0.1
 ##################################################
  accordion: ^2.6.0
  calendar_date_picker2: ^1.0.2
  custom_radio_grouped_button: ^2.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/en.json
    - assets/translations/ar.json