name: baraneq
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
####################### basic ############################
  dartz: ^0.10.1
  dio: ^5.3.2
  get_it: ^7.6.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_offline: ^3.0.0
  internet_connection_checker: ^1.0.0+1
  jwt_decode: ^0.3.1
  flutter_screenutil: ^5.9.0
  page_transition: ^2.0.9
  path_provider: ^2.1.3
  #persistent_bottom_nav_bar: ^5.0.2
  flutter_secure_storage: ^9.2.2
  supercharged: ^2.1.1
  #google_fonts: ^6.1.0
  url_launcher: ^6.1.14
  # introduction_screen: ^3.1.12
  avatar_glow: ^3.0.1
  image_picker: ^1.0.4
  #material_floating_search_bar_2: ^0.5.0
  loader_overlay: ^4.0.0
  quickalert: ^1.1.0
####################### Not used ############################
  # cached_network_image: ^3.2.3
  # geocoding: ^2.1.0
  # geolocator: ^10.0.0 
  # flutter_map: ^6.1.0
  # google_maps_flutter: ^2.5.0
  # google_nav_bar: ^5.0.6
  # latlong2: ^0.9.0
  # pinput: ^4.0.0
  # shimmer: ^3.0.0
  # simple_animations: ^5.0.2
  # lottie: ^3.0.0
  # card_swiper: ^3.0.1
 ##################################################
  #calendar_date_picker2: ^1.0.2
  custom_radio_grouped_button: ^2.2.1
  syncfusion_flutter_datagrid: ^26.1.39
  syncfusion_localizations: ^26.1.39
  intl: ^0.19.0
  printing: ^5.12.0
  open_file: ^3.3.2
  flutter_speed_dial: ^7.0.0
  window_manager: ^0.3.9
  
  sqflite_common_ffi: ^2.3.3
  syncfusion_flutter_pdf: ^26.1.39
  open_filex: ^4.4.0
  searchfield: ^1.0.5
  date_field: ^5.2.1
  dropdown_button2: ^2.3.9
  another_flushbar: ^1.12.30

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  msix: ^3.16.7
msix_config:
  display_name: baraneq
  publisher_display_name: ama
  identity_name: ama
  msix_version: 1.0.0.0
  logo_path: D:\Custom_Projects\baraneq\assets\icons\appicon.png


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/appicon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/appicon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/appicon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/appicon.png"
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/en.json
    - assets/translations/ar.json
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo/Cairo-ExtraLight.ttf
          weight: 800
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
          weight: 900
        - asset: assets/fonts/Cairo/Cairo-Light.ttf
          weight: 300
